[project]
name = "staff_loans"
authors = [
    { name = "VV System Developers LTD", email = "ibrahim@vvsdtz.com" }
]
description = "An App that manages staff loans and loan rescheduling"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = []

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
frappe = ">=16.0.0,<17.0.0"

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "I",
    "UP",
    "B",
]
ignore = [
    "E501",
    "E402",
    "E741",
]
